{
    "name": "Cars Detailing and Servicing",
    "category": "Services/Automotive",
    "license": "LGPL-3",
    'sequence': 1,
    'summary': 'Manage car detailing, washing, and other automotive services',
    'description': """
        This module allows businesses to manage car detailing and service bookings, track service history,
        customer vehicles, pricing, and staff assignments.
    """,
    "author": "Kaushik Rabari",
    "images": ["static/description/image.jpg"],
    "depends": ['base', 'website', 'contacts', 'sale', 'sale_management', 'fleet'],
    "data": [
        "security/field_access_rules.xml",
        "security/field_access.xml",
        "security/ir.model.access.csv",
        "data/email_templates.xml",
        "data/ir_cron.xml",
        "data/job_sequence_sheet.xml",
        "views/vehicle_views.xml",
        "views/service_type_views.xml",
        "views/booking_views.xml",
        "views/technician_views.xml",
        "views/vehicle_job_sheet_views.xml",
        "views/vehicle_invoice.xml",
        "views/portal_templates.xml",
        "report/detailed_service_reports.xml",
        "report/detailed_service_template.xml",
        "report/invoice_reports.xml",
        "report/invoice_report_template.xml",
        "wizard/job_sheet_manipulate.xml",
    ],
    # 'assets': {
    #     'web.assets_backend': [
    #         'car_detailing_services/static/src/js/payment_status_display.js',
    #         'car_detailing_services/static/src/xml/statusbar_time.xml',
    #     ],
    # },
    "installable": True,
    "application": True,
}
